### PR TITLE
test: run tests on webworkers

### PR DESCRIPTION
**Pull request by daviddias**
@dryajov

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@diasdavid can we finally retire this module... we are not using it anymore internally

**Comment by daviddias** [comment]
ping @dryajov

**Comment by dryajov** [comment]
on it.

**Comment by dryajov** [comment]
This requires https://github.com/diasdavid/webcrypto/pull/17

cc @diasdavid

**Comment by daviddias** [comment]
@dryajov merged and released

**Comment by dryajov** [comment]
Woot! All green!

cc @diasdavid

**Pull request merged**
